spring:
  application:
    name: elment_crud
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crud?serverTimezone=GMT%2B8
    username: root
    password: root
